{
 "title": "NTM - Nexus Interfaces",
 "tags": [
  "cisco",
  "Nexus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "${VAR_DB}" },
   { "name": "rp", "label": "Retention Policy", "query": "${VAR_RP}" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "switchname",
    "label": "Switch Name",
    "query": "show tag values from  \"$db\".\"$rp\".\"Switches\" with key=switchname WHERE type='nexus' and $timeFilter"
   },
   {
    "name": "switch",
    "label": "Switch",
    "query": "select last(switch) from (select model,switch from \"$db\".\"$rp\".\"Switches\" where switchname =~ /$switchname/ and type='nexus' and $timeFilter)"
   },
   {
    "name": "intf",
    "label": "Interfaces",
    "query": "show tag values from \"$db\".\"$rp\".\"SwitchIntfStats\" with key=intf where switchname =~ /$switchname/ and type='nexus' and $timeFilter"
   },
   {
    "name": "min_interval",
    "query": "select last(elapsed) from (select elapsed(model,1s) from \"$db\".\"$rp\".\"Switches\" where switchname =~ /$switchname/ and type='nexus' and $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/cisco_logo.png' width=\"90\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>NTM - Nexus Traffic Monitoring - Interfaces</strong></span></h2>\n<h5 style=\"text-align: center; margin: 0px;\"><span style=\"color: #ff00ff;\">Interface(s) - ${intf}</span></span></h5>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/your_logo.png' alt=\"\" width=\"90\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT location as Location, last(description) as \"Description\", oper_state as \"Operational State\", oper_mode as \"Oper Mode\", oper_speed as \"Speed\", switchname as \"Switch Name\", peer as \"Peer\", peer_intf as \"Peer Interface\", peer_type as \"Peer Type\", peer_name as \"Peer Name\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ and type='nexus' and \"intf\" =~ /^$intf$/) AND  $timeFilter GROUP BY switch,intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic on $intf on $switchname (${min_interval}-sec Avg)",
   "type": "timeseries",
   "description": "Uses NTM collector to show average utilization of the collection interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"RX Traffic\") as \"RX Traffic\" from(SELECT non_negative_difference(rx_bytes)*8/(elapsed(rx_bytes,1ms)/1000) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter group by intf,peer,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), intf,peer,peer_name,peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\") as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/(elapsed(tx_bytes,1ms)/1000) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter group by intf,peer,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), intf,peer,peer_name,peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic on $intf on $switchname (1-sec Avg)",
   "type": "timeseries",
   "description": "Uses GNMI OpenConfig export to show average utilization of the sample interval. This data is not collected by the NTM collector and it must be configured separately.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\") as \"TX Traffic\" from (SELECT non_negative_difference(\"out_octets\")*8/(elapsed(out_octets)/1000000000) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"oc_int_counters\" WHERE (\"source\"::tag = '172.22.36.56') AND (\"name\"::tag =~ /^$intf$/) AND $timeFilter) where  $timeFilter GROUP BY time($__interval), \"name\"::tag ",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"RX Traffic\") as \"RX Traffic\" from (SELECT non_negative_difference(\"in_octets\")*8/(elapsed(in_octets)/1000000000) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"oc_int_counters\" WHERE (\"source\"::tag = '172.22.36.56') AND (\"name\"::tag =~ /^$intf$/) AND $timeFilter) where  $timeFilter GROUP BY time($__interval), \"name\"::tag ",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors on $intf on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX CRC\" from(SELECT non_negative_difference(rx_crc) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf,peer_name,peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX CRC Stomped\" from(SELECT non_negative_difference(rx_crc_stomped) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf, peer_name, peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "% Utilization on $intf on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"RX Traffic\")/(max(\"speed\")*1000000000) as \"RX Traffic\" from(SELECT non_negative_difference(rx_bytes)*8/(elapsed(oper_speed,1ms)/1000)as \"RX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter group by intf,peer,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), intf, peer,peer_name,peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\")/(max(\"speed\")*1000000000) as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/(elapsed(oper_speed,1ms)/1000) as \"TX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter group by intf,peer,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), intf,peer,peer_name,peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Packet Distribution on $intf on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX <64 bytes\" from(SELECT non_negative_difference(rxPkts64Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX 65 - 127 bytes\" from(SELECT non_negative_difference(rxPkts65to127Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX 128 - 255 bytes\" from(SELECT non_negative_difference(rxPkts128to255Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX 256 - 511 bytes\" from(SELECT non_negative_difference(rxPkts256to511Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX 512 - 1023 bytes\" from(SELECT non_negative_difference(rxPkts512to1023Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX 1024 - 1518 bytes\" from(SELECT non_negative_difference(rxPkts1024to1518Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX Jumbo\" from(SELECT non_negative_difference(rx_jumbo) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Packet Distribution on $intf on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX <64 bytes\" from(SELECT non_negative_difference(txPkts64Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX 65 - 127 bytes\" from(SELECT non_negative_difference(txPkts65to127Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX 128 - 255 bytes\" from(SELECT non_negative_difference(txPkts128to255Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX 256 - 511 bytes\" from(SELECT non_negative_difference(txPkts256to511Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX 512 - 1023 bytes\" from(SELECT non_negative_difference(txPkts512to1023Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX 1024 - 1518 bytes\" from(SELECT non_negative_difference(txPkts1024to1518Octets) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX Jumbo\" from(SELECT non_negative_difference(tx_jumbo) FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Queue Drops on $intf on $switchname",
   "type": "timeseries",
   "description": "These are the drops in the ingress queues caused by the PFC Watchdog feature as reported by the NX-OS command show queuing pfc-queue detail. Ingress queues are relevant only when PFC is enabled.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(non_negative_difference) as \"Dropped Packets\" from(SELECT non_negative_difference(drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter group by q) where $timeFilter GROUP BY time($__interval), intf, q",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Drops on $intf on $switchname",
   "type": "timeseries",
   "description": "These are WRED/AFD & tail drops reported by the NX-OS command show queuing interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "select max(\"non_negative_difference\") as \"Random Drops\" from(SELECT non_negative_difference(rand_drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter GROUP BY switch,intf,q,peer,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer, peer_intf"
    },
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "select max(\"non_negative_difference\") as \"TX Drops\" from(SELECT non_negative_difference(drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter GROUP BY switch,intf,q,peer,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer, peer_intf"
    }
   ]
  },
  {
   "title": "TX Pause Frame Monitoring Compared with RX Traffic on $intf on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "select max(\"non_negative_difference\") as \"TX Pause\" from(SELECT non_negative_difference(tx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter GROUP BY switch,intf,q,peer,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer, peer_intf"
    },
    {
     "alias": "$col $tag_intf",
     "query": "select max(\"RX Traffic\") as \"RX Traffic\" from(SELECT non_negative_difference(rx_bytes)*8/(elapsed(oper_speed,1ms)/1000) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf"
    }
   ]
  },
  {
   "title": "RX Pause Frame Monitoring Compared with TX Traffic on $intf on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "select max(\"non_negative_difference\") as \"RX Pause\" from(SELECT non_negative_difference(rx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter GROUP BY switch,intf,q,peer,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer, peer_intf"
    },
    {
     "alias": "$col $tag_intf",
     "query": "select max(\"TX Traffic\") as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/(elapsed(oper_speed,1ms)/1000) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf"
    }
   ]
  },
  {
   "title": "ECN Counters on $intf on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "select max(\"non_negative_difference\") as \"ECN Marked Pkts\" from(SELECT non_negative_difference(ecn_marked_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter GROUP BY switch,intf,q,peer,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer, peer_intf"
    }
   ]
  },
  {
   "title": "Queue Utilization on $intf on $switchname",
   "type": "timeseries",
   "description": "This is the instant value at the time of collection",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "SELECT max(\"q_depth\") AS \"Q Depth\" FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE \"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/ and $timeFilter GROUP BY time($__interval), switch,intf,q,peer,peer_intf fill(linear)\n"
    }
   ]
  },
  { "title": "Beta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Burst (Left y-axis show peak buffer utilization (bar). Right y-axis show duration of burst (point))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q",
     "query": "SELECT peak as \"Peak\" FROM \"$db\".\"$rp\".\"SwitchBurst\" WHERE \"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/ AND $timeFilter GROUP BY intf, q"
    },
    {
     "alias": "$col $tag_intf  $tag_q",
     "query": "SELECT \"duration\" as \"Duration\" FROM \"$db\".\"$rp\".\"SwitchBurst\" WHERE \"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/ AND $timeFilter GROUP BY intf, q"
    }
   ]
  },
  {
   "title": "Per Queue Egress Traffic on $intf on $switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\") as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/(elapsed(tx_bytes,1ms)/1000) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"intf\" =~ /^$intf$/) AND $timeFilter group by q) where $timeFilter GROUP BY time($__interval), intf, q",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  }
 ]
}