{
 "title": "NTM - Nexus Switch Monitoring",
 "tags": [
  "Nexus",
  "cisco"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "${VAR_DB}" },
   { "name": "rp", "label": "Retention Policy", "query": "${VAR_RP}" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "switchname",
    "label": "Switch Name",
    "query": "show tag values from  \"$db\".\"$rp\".\"Switches\" with key=switchname WHERE type='nexus' and $timeFilter "
   },
   {
    "name": "min_interval",
    "query": "select last(elapsed) from (select elapsed(model,1s) from \"$db\".\"$rp\".\"Switches\" where switchname =~ /$switchname/ and type='nexus' and $timeFilter)"
   },
   { "name": "min_interval_sum", "query": "${VAR_MIN_INTERVAL_SUM}" },
   {
    "name": "peer_switch_name",
    "label": "Peer Switch Name",
    "query": "show tag values from  \"$db\".\"$rp\".\"SwitchIntfStats\" with key=peer_name  WHERE type='nexus' and switchname =~ /$switchname/ and peer_type='switch' and $timeFilter "
   },
   {
    "name": "switch",
    "query": "select last(switch) from (select model,switch from \"$db\".\"$rp\".\"Switches\" where switchname =~ /$switchname/ and type='nexus1' and $timeFilter)"
   },
   {
    "name": "peer_switches",
    "query": "select last(switch) from (select model,switch from \"$db\".\"$rp\".\"Switches\" where switchname =~ /$peer_switch_name/ and type='nexus' and $timeFilter group by peer_switch_name) group by peer_switch_name"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/cisco_logo.png' width=\"90\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>NTM - Nexus Traffic Monitoring - Switches</strong></span></h2>\n<h5 style=\"text-align: center; margin: 0px;\"><span style=\"color: #ff00ff;\">Switch(es) - ${switchname}</span></span></h5>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/your_logo.png' alt=\"\" width=\"90\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"model\"),location FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"switchname\") from (select model,switchname FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"switch\") from (select model,switch FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_ver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "NX-OS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT last(\"sys_ver\") FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_ver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "# Interfaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and $timeFilter GROUP BY switch,intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kernel Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"kernel_uptime\") AS \"Uptime\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(\"cpu_user\") AS \"CPU User\", mean(\"cpu_kernel\") AS \"CPU Kernel\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "cpu_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU User" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_kernel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU Kernel" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Kernel - % CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(\"cpu_kernel\") as \"Kernel - % CPU\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User - % CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(\"cpu_user\") as \"User - % CPU\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"400G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"oper_speed\" = 400) and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"100G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"oper_speed\" = 100) and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"25G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"oper_speed\" = 25) and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"10G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"1G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"oper_speed\" = 1) and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Mode",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"access\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ and oper_mode = 'access') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"trunk\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ and oper_mode = 'trunk') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peer Device Type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Switch\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"switchname\" =~ /^$switchname$/ and peer_type='switch') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Host\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"switchname\" =~ /^$switchname$/ and peer_type='host') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT (mean(mem_used)/mean(mem_total)) as \"Mem Used %\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT last(\"mem_used\")/last(\"mem_total\")*100 FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Up\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"switchname\" =~ /^$switchname$/ and oper_state = 'up' and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Down\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"switchname\" =~ /^$switchname$/ and oper_state = 'down' and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"None\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ and oper_state = 'None') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Unknown\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ and oper_state = '') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Down Reason",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Admin Down\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"down_reason\" = 'admin-down') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"XCVR Absent\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"down_reason\" = 'xcvr-absent') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Link Failure\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/ AND \"down_reason\" = 'link-failure') and $timeFilter GROUP BY time($__interval),intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NXAPI Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(response_time) as \"Response Time\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Inventory",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(description) as \"Description\", oper_state as \"Operational State\", peer as \"Peer Device\", peer_type as \"Peer Type\", peer_name as \"Peer Device Name\", peer_intf as \"Peer Interface\", oper_mode as \"Oper Mode\", down_reason as \"Down Reason\", oper_speed as \"Speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"switchname\" =~ /^$switchname$/ AND  $timeFilter GROUP BY intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"RX Traffic\") as \"RX\" from(SELECT non_negative_difference(rx_bytes)*8/elapsed(oper_speed,1s)as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY intf,switch) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"TX Traffic\") as \"TX\" from(SELECT non_negative_difference(tx_bytes)*8/elapsed(oper_speed,1s)as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY intf,switch) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"non_negative_difference_elapsed\") as \"Total CRC\" from (SELECT non_negative_difference(max(rx_crc))/elapsed(max(oper_speed),1s)  FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"oper_state\" != 'down'  and \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY intf,time($__interval)) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"non_negative_difference_elapsed\") as \"Total CRC Stomped\" from (SELECT non_negative_difference(max(rx_crc_stomped))/elapsed(max(oper_speed),1s)  FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"oper_state\" != 'down'  and \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY intf,time($__interval)) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"last_first\") as \"Total Random Dropped Packets\" from (SELECT last(rand_drop_pkts) - first(rand_drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by intf,q) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"last_first\") as \"Total Dropped Packets\" from (SELECT last(drop_pkts) - first(drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by intf,q) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingress Utilization",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "non" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"RX Traffic\")/(max(\"speed\")*1000000000) as \"% RX Utilization\", max(\"speed\") as \"Speed\" from (SELECT non_negative_difference(rx_bytes)*8/elapsed(oper_speed,1s)as \"RX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY intf,switchname) where $timeFilter GROUP BY intf, switchname",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Egress Utilization",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"TX Traffic\")/(max(\"speed\")*1000000000) as \"% TX Utilization\", max(\"speed\") as \"Speed\" from(SELECT non_negative_difference(tx_bytes)*8/elapsed(oper_speed,1s)as \"TX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY intf,switchname) where $timeFilter GROUP BY intf, switchname",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - CRC",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 12, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,10) as \"CRC\" from (select max(\"CRC\") from(SELECT last(rx_crc) - first(rx_crc) as \"CRC\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by intf) where $timeFilter GROUP BY intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - CRC Stomped",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 15, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,10) as \"Stomped CRC\" from (select max(\"CRC\") from(SELECT last(rx_crc_stomped) - first(rx_crc_stomped) as \"CRC\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by intf) where $timeFilter GROUP BY intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - Random Drops",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,10) as \"Drops\" from (select max(\"last_first\") from(SELECT last(rand_drop_pkts) - first(rand_drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by intf,q) where $timeFilter GROUP BY intf,q) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - Drops",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,q,10) as \"Drops\" from (select max(\"last_first\") from (SELECT last(drop_pkts) - first(drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by intf,q) where $timeFilter GROUP BY intf,q) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 45 },
   "options": {
    "content": "<h2 style=\"text-align: center;\"><span style=\"background-color: #00ff00;color: black\">Core</span> Interfaces</h2>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 45 },
   "options": {
    "content": "<h2 style=\"text-align: center;\"><span style=\"background-color: #00ffff;color: black\">Edge</span> Interfaces</h2>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Core Ports - RX Pause (Egress Congestion)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"last_first\") as \"RX Pause\" from(SELECT last(rx_pause) - first(rx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter and peer_type='switch' group by intf,q,peer_name,peer,peer_intf) where $timeFilter GROUP BY intf,q,peer_name,peer,peer_intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edge Ports - RX Pause (Egress Congestion)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"last_first\") as \"RX Pause\" from(SELECT last(rx_pause) - first(rx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter and peer_type='host' group by intf,q,peer_name,peer,peer_intf) where $timeFilter GROUP BY intf,q,peer_name,peer,peer_intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Core Ports - TX Pause (Ingress Congestion)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"last_first\") as \"TX Pause\" from(SELECT last(tx_pause) - first(tx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter and peer_type='switch' group by intf,q,peer_name,peer,peer_intf) where $timeFilter GROUP BY intf,q,peer_name,peer,peer_intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edge Ports - TX Pause (Ingress Congestion)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"last_first\") as \"TX Pause\" from(SELECT last(tx_pause) - first(tx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter and peer_type='host' group by intf,q,peer_name,peer,peer_intf) where $timeFilter GROUP BY intf,q,peer_name,peer,peer_intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Core Interfaces - ECN Marked Packets (Egress Congestion)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"last_first\") as \"ECN Marked Packets\" from(SELECT last(ecn_marked_pkts) - first(ecn_marked_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter and peer_type='switch' \n group by intf,q,peer_name,peer,peer_intf) where $timeFilter GROUP BY intf,q,peer_name,peer,peer_intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Edge Interfaces - ECN Marked Packets (Egress Congestion)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(\"last_first\") as \"ECN Marked Packets\" from(SELECT last(ecn_marked_pkts) - first(ecn_marked_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter group by intf,q,peer_name,peer_type,peer,peer_intf) where $timeFilter and peer_type='host' GROUP BY intf,q,peer_name,peer,peer_intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX Pause (Egress Congestion) on Core Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX Pause\" from(SELECT non_negative_difference(rx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter GROUP BY switch,intf,q,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer_name, peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Pause (Egress Congestion) on Edge Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"RX Pause\" from(SELECT non_negative_difference(rx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter GROUP BY switch,intf,q,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer_name, peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Pause (Ingress Congestion) on Core Interfaces $switchname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX Pause\" from(SELECT non_negative_difference(tx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter GROUP BY switch,intf,q,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer_name, peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Pause (Ingress Congestion) on Edge Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"TX Pause\" from(SELECT non_negative_difference(tx_pause) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter GROUP BY switch,intf,q,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer_name, peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "PFC Watchdog (Severe Egress Congestion) on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf Grp-$tag_qosgrp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select sum(\"non_negative_difference\") as \"Shutdown\" from(SELECT non_negative_difference(shutdown) FROM \"$db\".\"$rp\".\"SwitchPFCWD\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY switch,intf,qosgrp) where $timeFilter GROUP BY time($__interval), switch,intf, qosgrp",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col $tag_intf Grp-$tag_qosgrp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select sum(\"non_negative_difference\") as \"Restored\" from(SELECT non_negative_difference(restored) FROM \"$db\".\"$rp\".\"SwitchPFCWD\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY switch,intf,qosgrp) where $timeFilter GROUP BY time($__interval), switch,intf, qosgrp",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "PFC Watchdog Stats (Severe Egress Congestion) on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf Grp-$tag_qosgrp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select sum(\"non_negative_difference\") as \"Drained\" from(SELECT non_negative_difference(\"pkt-drained\") FROM \"$db\".\"$rp\".\"SwitchPFCWD\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY switch,intf,qosgrp) where $timeFilter GROUP BY time($__interval), switch,intf, qosgrp",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col $tag_intf Grp-$tag_qosgrp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select sum(\"non_negative_difference\") as \"Dropped\" from(SELECT non_negative_difference(\"pkt-dropped\") FROM \"$db\".\"$rp\".\"SwitchPFCWD\" WHERE (\"switchname\" =~ /^$switchname$/) AND $timeFilter GROUP BY switch,intf,qosgrp) where $timeFilter GROUP BY time($__interval), switch,intf, qosgrp",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Drops on Core Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"Drops\" from(SELECT non_negative_difference(drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter GROUP BY switch,intf,q,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer_name, peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Drops on Edge Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"non_negative_difference\") as \"Drops\" from(SELECT non_negative_difference(drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter GROUP BY switch,intf,q,peer_name,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer_name, peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Traffic on Core Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"RX Traffic\") as \"RX Traffic\" from(SELECT non_negative_difference(rx_bytes)*8/elapsed(oper_speed,1s) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf, peer_name,peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Traffic on Edge Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"RX Traffic\") as \"RX Traffic\" from(SELECT non_negative_difference(rx_bytes)*8/elapsed(oper_speed,1s) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf, peer_name,peer_intf\n",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Traffic on Core Interfaces $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\") as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/elapsed(oper_speed,1s) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf,peer_name,peer_intf",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Traffic on Edge Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\") as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/elapsed(oper_speed,1s) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf,peer_name,peer_intf\n",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "RX % Utilization on Core Interfaces $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"RX Traffic\")/(max(\"speed\")*1000000000) as \"RX Traffic\" from(SELECT non_negative_difference(rx_bytes)*8/elapsed(oper_speed,1s)as \"RX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf,peer_name,peer_intf\n",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "RX % Utilization on Edge Interfaces $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col $tag_intf <-- $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"RX Traffic\")/(max(\"speed\")*1000000000) as \"RX Traffic\" from(SELECT non_negative_difference(rx_bytes)*8/elapsed(oper_speed,1s)as \"RX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf,peer_name,peer_intf\n",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "TX % Utilization on Core Interfaces $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\")/(max(\"speed\")*1000000000) as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/elapsed(oper_speed,1s)as \"TX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf,peer_name,peer_intf\n",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "TX % Utilization on Edge Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col $tag_intf --> $tag_peer_name $tag_peer_intf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "select max(\"TX Traffic\")/(max(\"speed\")*1000000000) as \"TX Traffic\" from(SELECT non_negative_difference(tx_bytes)*8/elapsed(oper_speed,1s)as \"TX Traffic\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter) where $timeFilter GROUP BY time($__interval), intf,peer_name,peer_intf\n",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "ECN Counters (Egress Congestion) on Core Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "select max(\"non_negative_difference\") as \"ECN Marked Pkts\" from(SELECT non_negative_difference(ecn_marked_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='switch' AND $timeFilter GROUP BY switch,intf,q,peer,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer, peer_intf"
    }
   ]
  },
  {
   "title": "ECN Counters (Egress Congestion) on Edge Interfaces on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q --> $tag_peer $tag_peer_intf",
     "query": "select max(\"non_negative_difference\") as \"ECN Marked Pkts\" from(SELECT non_negative_difference(ecn_marked_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"switchname\" =~ /^$switchname$/) and peer_type='host' AND $timeFilter GROUP BY switch,intf,q,peer,peer_intf) where $timeFilter GROUP BY time($__interval), switch,intf, q, peer, peer_intf"
    }
   ]
  },
  {
   "title": "Burst Size on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT peak as \"Peak\" FROM \"$db\".\"$rp\".\"SwitchBurst\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY intf, q",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Burst Duration on $switchname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT \"duration\" as \"Duration\" FROM \"$db\".\"$rp\".\"SwitchBurst\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY intf, q",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Burst (Left y-axis show peak buffer utilization in bytes using bars. Right y-axis show duration of burst in microseconds using point)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col $tag_intf $tag_q",
     "query": "SELECT peak as \"Peak\" FROM \"$db\".\"$rp\".\"SwitchBurst\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY intf, q"
    },
    {
     "alias": "$col $tag_intf  $tag_q",
     "query": "SELECT \"duration\" as \"Duration\" FROM \"$db\".\"$rp\".\"SwitchBurst\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY intf, q"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Distribution on $switchname on links to $peer_switch_name",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 150 },
     "repeat": "peer_switch_name",
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "$col $tag_intf <-- $tag_peer_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT (non_negative_difference(mean(rx_bytes))/elapsed(mean(oper_speed),1s))*8 as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"switchname\" =~ /^$switchname$/) and \"peer_name\" =~ /$peer_switch_name$/ AND $timeFilter GROUP BY time($__interval),intf, peer_name",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Beta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peak No-Drop Buffer Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col Instance $tag_instance",
       "query": "SELECT peak_cell_no_drop as \"Peak usage no-drop\" FROM  \"$db\".\"$rp\".\"SwitchBufferStats\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY instance,sw"
      },
      {
       "alias": "$col Instance",
       "query": "SELECT max(cell_count_no_drop_pg) as \"Max allowed cells no-drop\" FROM  \"$db\".\"$rp\".\"SwitchBufferStats\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter group by time($__interval)"
      }
     ]
    },
    {
     "title": "Peak Drop Buffer Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col Instance $tag_instance",
       "query": "SELECT peak_cell_drop_pg as \"Peak usage drop\" FROM  \"$db\".\"$rp\".\"SwitchBufferStats\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter GROUP BY instance"
      },
      {
       "alias": "$col Instance",
       "query": "SELECT max(cell_count_drop_pg) as \"Max allowed cells drop\" FROM  \"$db\".\"$rp\".\"SwitchBufferStats\" WHERE \"switchname\" =~ /^$switchname$/ AND $timeFilter group by time($__interval)"
      }
     ]
    }
   ]
  }
 ]
}