{
 "title": "NTM - Locations",
 "tags": [
  "Nexus",
  "cisco"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "${VAR_DB}" },
   { "name": "rp", "label": "Retention Policy", "query": "${VAR_RP}" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "location",
    "label": "Location",
    "query": "show tag values from \"$db\".\"$rp\".\"Switches\" with key=location where type='nexus' and $timeFilter"
   },
   {
    "name": "min_interval",
    "query": "select last(elapsed) from (select elapsed(switchname,1s) from \"$db\".\"$rp\".\"Switches\" where location =~ /$location/ and type='nexus' and $timeFilter)"
   },
   { "name": "min_interval_sum", "query": "${VAR_MIN_INTERVAL_SUM}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/cisco_logo.png' width=\"90\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>NTM - Nexus Traffic Monitoring - Locations</strong></span></h2>\n<h5 style=\"text-align: center; margin: 0px;\"><span style=\"color: #ff00ff;\">Location(s) - ${location}</span></span></h5>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/your_logo.png' alt=\"\" width=\"90\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "# Total Locations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Switches\" WHERE type='nexus' and $timeFilter GROUP BY time($__interval),location) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Switches in $location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Switches\" WHERE type='nexus' and (\"location\" =~ /^$location$/) and $timeFilter GROUP BY time($__interval),switch) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Interfaces in $location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/) and $timeFilter GROUP BY switch,intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Hosts in $location",
   "type": "stat",
   "description": "Hosts connected to switchports and discovered using LLDP",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(peer_name) from (select peer_name,last(tx_bytes) from \"$db\".\"$rp\".\"SwitchIntfStats\" where peer_type='host' and (\"location\" =~ /^$location$/) and $timeFilter group by peer_name) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peer Device Type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Switch\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and peer_type='switch') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Host\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and peer_type='host') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"400G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"oper_speed\" = 400) and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"100G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"oper_speed\" = 100) and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"25G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"oper_speed\" = 25) and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"10G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"1G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"oper_speed\" = 1) and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Mode",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"access\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and oper_mode = 'access') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"trunk\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and oper_mode = 'trunk') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Up\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and oper_state = 'up') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Down\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and oper_state = 'down') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"None\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and oper_state = 'None') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Unknown\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and oper_state = '') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Down Reason",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Admin Down\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"down_reason\" = 'admin-down') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"XCVR Absent\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"down_reason\" = 'xcvr-absent') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Link Failure\" from (SELECT last(\"rx_bytes\") FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ AND \"down_reason\" = 'link-failure') and $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Inventory",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT switchname as \"Switch Name\", last(sys_ver) as \"NX-OS Version\", kernel_uptime as \"Kernel Uptime\",model as \"Switch Model\", cpu_kernel as \"CPU Util - Kernel\", cpu_user as \"CPU Util - User\", (\"mem_used\")/(\"mem_total\")*100 as \"Memory Util\", response_time as \"Response Time\" FROM \"$db\".\"$rp\".\"Switches\" WHERE type='nexus' and (\"location\" =~ /^$location$/) AND  $timeFilter GROUP BY switch,location",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Inventory",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT switchname as \"Switch Name\", location as \"Location\", last(description) as \"Description\", oper_state as \"Operational State\", oper_mode as \"Oper Mode\", down_reason as \"Down Reason\", oper_speed as \"Speed\", peer as \"Peer Device\", peer_type as \"Peer Type\", peer_name as \"Peer Name\", peer_intf as \"Peer Interface\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/) AND  $timeFilter GROUP BY switch,intf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switchport Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"RX Traffic\") as \"Total RX Traffic\" from (SELECT non_negative_difference(max(rx_bytes))*8/elapsed(max(oper_speed),1s) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE type='nexus' and (\"location\" =~ /^$location$/ and oper_state != 'down') AND $timeFilter GROUP BY time(${__interval}),switch,intf) where $timeFilter GROUP BY time(${__interval})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"TX Traffic\") as \"Total TX Traffic\" from (SELECT non_negative_difference(mean(tx_bytes))*8/elapsed(mean(oper_speed),1s) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"location\" =~ /^$location$/ and type='nexus' and oper_state != 'down') AND $timeFilter GROUP BY time($__interval),switch,intf) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Utilized Ports - % RX",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"util\",intf,switchname,Speed, peer_type,peer_name,peer_intf,10) as \"% RX Utilization\" from (select max(\"gbps\")*100/max(\"speed\") as \"util\", max(\"speed\") as \"Speed\" from (SELECT derivative(rx_bytes)*8/1000000000 as \"gbps\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Utilized Ports - % TX",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"util\",intf,switchname,Speed, peer_type,peer_name,peer_intf,10) as \"% TX Utilization\" from (select max(\"gbps\")*100/max(\"speed\") as \"util\", max(\"speed\") as \"Speed\" from (SELECT derivative(tx_bytes)*8/1000000000 as \"gbps\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Utilized Ports - Absolute RX",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"util\",intf,switchname,Speed, peer_type,peer_name,peer_intf,10) as \"RX Throughput\" from (select max(\"gbps\") as \"util\", max(\"speed\") as \"Speed\" from (SELECT derivative(rx_bytes)*8/1000000000 as \"gbps\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Utilized Ports - Absolute TX",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"util\",intf,switchname,Speed, peer_type,peer_name,peer_intf,10) as \"TX Throughput\" from (select max(\"gbps\") as \"util\", max(\"speed\") as \"Speed\" from (SELECT derivative(tx_bytes)*8/1000000000 as \"gbps\", last(oper_speed) as \"speed\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"max\") as \"CRC\" from (select max(\"CRC\") from(SELECT last(rx_crc) - first(rx_crc) as \"CRC\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"max\") as \"Stomped CRC\" from (select max(\"CRC\") from(SELECT last(rx_crc_stomped) - first(rx_crc_stomped) as \"CRC\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - CRC",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,switchname,peer_type,peer_name,peer_intf,10) as \"CRC\" from (select max(\"CRC\") from(SELECT last(rx_crc) - first(rx_crc) as \"CRC\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - Stomped CRC",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,switchname,peer_type,peer_name,peer_intf,10) as \"Stomped CRC\" from (select max(\"CRC\") from(SELECT last(rx_crc_stomped) - first(rx_crc_stomped) as \"CRC\" FROM \"$db\".\"$rp\".\"SwitchIntfStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"last_first\") as \"Total Random Dropped Packets\" from (SELECT last(rand_drop_pkts) - first(rand_drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,q) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"last_first\") as \"Total Dropped Packets\" from (SELECT last(drop_pkts) - first(drop_pkts) FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,q) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - Random Drops",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,switchname,peer_type,peer_name,peer_intf,10) as \"Random Drops\" from (select max(\"rand_drop_pkts\") from(SELECT last(rand_drop_pkts) - first(rand_drop_pkts) as \"rand_drop_pkts\" FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Ports - Drops",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"max\",intf,switchname,peer_type,peer_name,peer_intf,10) as \"Drops\" from (select max(\"drop_pkts\") from(SELECT last(drop_pkts) - first(drop_pkts) as \"drop_pkts\" FROM \"$db\".\"$rp\".\"SwitchQStats\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter group by intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter GROUP BY intf,switchname,peer_type,peer_name,peer_intf) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}